update

diff --git a/files/bash/cheatsheet b/files/bash/cheatsheet
--- a/files/bash/cheatsheet
+++ b/files/bash/cheatsheet
@@ -1,3 +1,34 @@
+# universal argument parser
+while (( "$#" )); do
+  case "$1" in
+    -f|--flag-with-argument)
+      FARG=$2
+      shift 2
+      ;;
+    --) # end argument parsing
+      shift
+      break
+      ;;
+    -*|--*=) # unsupported flags
+      echo "Error: Unsupported flag $1" >&2
+      exit 1
+      ;;
+    *) # preserve positional arguments
+      PARAMS="$PARAMS $1"
+      shift
+      ;;
+  esac
+done
+
+
+# all args
+echo "$@"
+
+# short substitutions
+state=off # or on!
+state=${state//off/disabled}
+state=${state//on/enabled}
+
 # Loop through file
 while read item; do
   echo "$item"
