June update

diff --git a/files/bash/cheatsheet b/files/bash/cheatsheet
--- a/files/bash/cheatsheet
+++ b/files/bash/cheatsheet
@@ -1,3 +1,36 @@
+# # # Misc # # #
+#
+cat msg.xml
+<?xml version = "1.0" encoding = "UTF-8"?>
+<alert xmlns = "urn:oasis:names:tc:emergency:cap:1.2">
+  <identifier>test</identifier>
+  <sent>2020-06-20T15:00:00-05:00</sent>
+  <msgType>Alert</msgType>
+  <info>
+    <headline>matchme</headline>
+  </info>
+</alert>
+msg="$(cat msg.xml)"
+curl -XPOST --data "$msg" http://127.0.0.1/....
+#
+#
+
+
+#  print current method name 
+${FUNCNAME[0]}
+
+# line-by-line file multiple delimieters:
+echo "12|23|11" | awk '{split($0,a,"|"); print a[3],a[2],a[1]}'
+
+# awk delimeters
+echo "1.2.4" | awk -F. '{print $1$2$3}'
+
+# switch on find command
+if [ -z $(find /var/log/crashes -name "app-*.log" ) ]
+then
+    echo "File is missing!"
+fi
+
 # glob evaluation
 compgen -G "/tmp/someFiles*
 
@@ -50,7 +83,7 @@ while (server_is_using "kworker"); do
   sleep 20
   [ -z "$start" ] && start="$(date +%s)"
   now=$(date +%s)
-  [ $(("$now" - "$start")) -le 360 ] || break # timeout after 6 mins
+  [ $((now-start)) -le 360 ] || break # timeout after 6 mins
 done
 # ------------------------------------------------------------------------------
 
@@ -106,6 +139,9 @@ for i in $(seq 1 100); do
   sed -i "0,/0000/ s/0000/$i/g" $FN # 0, substitutes the first match only
   grep -q "echo '0000'" $FN || break
 done
+#
+# poll for test breakage
+for i in $(seq 1 12); do bundle exec rspec spec || break; done
 
 
 # arrays
